"""LLM-backed strategy that wraps the prompt modules.

Only handles the criteria where deterministic / heuristic strategies
cannot produce a high-confidence patch and the LLM has clear value:

    - 1.1.1 image-alt (when no title/aria-label is present)
    - 1.4.3 color-contrast (when colors cannot be parsed from the inline style)

Adding new criteria here requires writing a prompt module under
`faro_spike/prompts/` and extending the dispatch in `fix()`.
"""

from __future__ import annotations

import json
import logging

from faro_spike.llm.provider import LLMCompletionError, LLMProvider
from faro_spike.models import Patch, Violation
from faro_spike.prompts import alt_text, contrast

logger = logging.getLogger(__name__)


class LLMRemediationStrategy:
    """Final fallback strategy backed by the configured LLMProvider."""

    name = "llm-remediation"
    cost_tier = "ai"
    supported_rules = frozenset({"image-alt", "color-contrast"})

    def __init__(self, *, provider: LLMProvider, max_tokens: int = 1024) -> None:
        self._provider = provider
        self._max_tokens = max_tokens

    def can_handle(self, violation: Violation) -> bool:
        return violation.rule_id in self.supported_rules

    def fix(self, violation: Violation) -> Patch | None:
        if not violation.nodes:
            return None
        if violation.rule_id == "image-alt":
            return self._fix_alt_text(violation)
        if violation.rule_id == "color-contrast":
            return self._fix_contrast(violation)
        return None

    # ------------------------------------------------------------------

    def _fix_alt_text(self, violation: Violation) -> Patch | None:
        node = violation.nodes[0]
        try:
            patched_html = self._provider.complete(
                system=alt_text.SYSTEM_PROMPT,
                user_message=alt_text.build_prompt(violation),
                max_tokens=self._max_tokens,
            ).strip()
        except LLMCompletionError as exc:
            logger.warning("llm_alt_text_failed", extra={"error": str(exc)})
            return None

        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=node.target[0] if node.target else "unknown",
            original_html=node.html,
            patched_html=patched_html,
            explanation=(
                f"Alt-text generated by {self._provider.name} from the page context. "
                "Review for accuracy before merging."
            ),
            confidence="medium",
        )

    def _fix_contrast(self, violation: Violation) -> Patch | None:
        node = violation.nodes[0]
        try:
            raw = self._provider.complete(
                system=contrast.SYSTEM_PROMPT,
                user_message=contrast.build_prompt(violation),
                max_tokens=self._max_tokens,
            )
        except LLMCompletionError as exc:
            logger.warning("llm_contrast_failed", extra={"error": str(exc)})
            return None

        try:
            payload = json.loads(raw)
            patched_color = payload["patched_color"]
            explanation = payload["explanation"]
        except (json.JSONDecodeError, KeyError):
            return None

        patched = self._inject_color(node.html, patched_color)
        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=node.target[0] if node.target else "unknown",
            original_html=node.html,
            patched_html=patched,
            explanation=explanation,
            confidence="low",
        )

    @staticmethod
    def _inject_color(html: str, color: str) -> str:
        if 'style="' in html:
            return html.replace('style="', f'style="color: {color}; ', 1)
        return html.replace("<", f'<span style="color: {color}">', 1) + "</span>"
