"""LLM-backed strategy that wraps the prompt modules.

Used as the last tier of the cascade. Only handles criteria where the
deterministic and heuristic strategies cannot infer the right answer
from the markup alone.
"""

from __future__ import annotations

import json
import logging
import re

from faro_spike.llm.provider import LLMCompletionError, LLMProvider
from faro_spike.models import Patch, Violation
from faro_spike.prompts import alt_text, button_name, contrast, link_name

logger = logging.getLogger(__name__)


class LLMRemediationStrategy:
    """Final fallback strategy backed by the configured LLMProvider."""

    name = "llm-remediation"
    cost_tier = "ai"
    supported_rules = frozenset({"image-alt", "color-contrast", "button-name", "link-name"})

    def __init__(self, *, provider: LLMProvider, max_tokens: int = 1024) -> None:
        self._provider = provider
        self._max_tokens = max_tokens

    def can_handle(self, violation: Violation) -> bool:
        return violation.rule_id in self.supported_rules

    def fix(self, violation: Violation) -> Patch | None:
        if not violation.nodes:
            return None
        dispatch = {
            "image-alt": self._fix_alt_text,
            "color-contrast": self._fix_contrast,
            "button-name": self._fix_button_name,
            "link-name": self._fix_link_name,
        }
        handler = dispatch.get(violation.rule_id)
        return handler(violation) if handler else None

    # ------------------------------------------------------------------

    def _fix_alt_text(self, violation: Violation) -> Patch | None:
        node = violation.nodes[0]
        try:
            patched_html = self._invoke(
                system=alt_text.SYSTEM_PROMPT,
                user=alt_text.build_prompt(violation),
            ).strip()
        except LLMCompletionError as exc:
            logger.warning("llm_alt_text_failed", extra={"error": str(exc)})
            return None

        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=node.target[0] if node.target else "unknown",
            original_html=node.html,
            patched_html=self._strip_code_fences(patched_html),
            explanation=(
                f"Alt-text generated by {self._provider.name} from the page context. "
                "Review for accuracy before merging."
            ),
            confidence="medium",
        )

    def _fix_contrast(self, violation: Violation) -> Patch | None:
        node = violation.nodes[0]
        try:
            raw = self._invoke(
                system=contrast.SYSTEM_PROMPT,
                user=contrast.build_prompt(violation),
            )
        except LLMCompletionError as exc:
            logger.warning("llm_contrast_failed", extra={"error": str(exc)})
            return None

        try:
            payload = json.loads(self._strip_code_fences(raw))
            patched_color = payload["patched_color"]
            explanation = payload["explanation"]
        except (json.JSONDecodeError, KeyError):
            return None

        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=node.target[0] if node.target else "unknown",
            original_html=node.html,
            patched_html=self._inject_color(node.html, patched_color),
            explanation=explanation,
            confidence="low",
        )

    def _fix_button_name(self, violation: Violation) -> Patch | None:
        return self._fix_open_tag(
            violation,
            tag="button",
            system=button_name.SYSTEM_PROMPT,
            user=button_name.build_prompt(violation),
            label="aria-label for <button>",
        )

    def _fix_link_name(self, violation: Violation) -> Patch | None:
        return self._fix_open_tag(
            violation,
            tag="a",
            system=link_name.SYSTEM_PROMPT,
            user=link_name.build_prompt(violation),
            label="aria-label for <a>",
        )

    # ------------------------------------------------------------------

    def _fix_open_tag(
        self,
        violation: Violation,
        *,
        tag: str,
        system: str,
        user: str,
        label: str,
    ) -> Patch | None:
        node = violation.nodes[0]
        try:
            patched_open = self._invoke(system=system, user=user)
        except LLMCompletionError as exc:
            logger.warning(
                "llm_open_tag_failed",
                extra={"rule_id": violation.rule_id, "error": str(exc)},
            )
            return None

        patched_open = self._strip_code_fences(patched_open).strip()
        if not patched_open.lower().startswith(f"<{tag}"):
            return None

        # Splice the new opening tag into the original HTML, preserving inner
        # content and the closing tag.
        opening_match = re.match(rf"<{tag}\b[^>]*>", node.html, flags=re.IGNORECASE)
        if not opening_match:
            return None
        new_open = patched_open if patched_open.endswith(">") else patched_open + ">"
        patched_html = new_open + node.html[opening_match.end():]

        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=node.target[0] if node.target else "unknown",
            original_html=node.html,
            patched_html=patched_html,
            explanation=(
                f"{label} generated by {self._provider.name} from the page context. "
                "Review for accuracy before merging."
            ),
            confidence="medium",
        )

    def _invoke(self, *, system: str, user: str) -> str:
        return self._provider.complete(
            system=system,
            user_message=user,
            max_tokens=self._max_tokens,
        )

    @staticmethod
    def _strip_code_fences(text: str) -> str:
        """Remove ```html ... ``` wrappers some models add."""
        cleaned = text.strip()
        if cleaned.startswith("```"):
            cleaned = re.sub(r"^```[a-zA-Z]*\n?", "", cleaned)
            cleaned = re.sub(r"\n?```$", "", cleaned)
        return cleaned.strip()

    @staticmethod
    def _inject_color(html: str, color: str) -> str:
        """Apply the new foreground color to the offending element.

        Strategy:
            1. If the element already has `style="..."`, prepend the color
               declaration so it wins over any later rule.
            2. If it has no style, splice `style="color: ..."` into the
               opening tag itself (BEFORE the closing `>` of the first tag).

        The previous version wrapped the whole snippet with a `<span>`,
        which produced invalid HTML when used on `<label>`, `<a>`, etc.
        """
        if 'style="' in html:
            return html.replace('style="', f'style="color: {color}; ', 1)

        opening_tag_end = html.find(">")
        if opening_tag_end == -1:
            return html  # cannot patch malformed input
        return (
            html[:opening_tag_end]
            + f' style="color: {color}"'
            + html[opening_tag_end:]
        )
