"""Generate code patches using Claude.

For the spike we cover two WCAG criteria with very different remediation
strategies:

    - 1.1.1 Non-text Content → Claude generates the alt-text from context.
    - 1.4.3 Contrast (Minimum) → Claude suggests a new color (in production
      we will switch this to the deterministic luminance algorithm and only
      keep the LLM as a fallback for complex backgrounds).

Any violation outside these two falls back to a "needs_human_review" patch
so the worker keeps a uniform output shape.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Final

from anthropic import Anthropic
from anthropic.types import MessageParam

from faro_spike.models import Patch, Violation
from faro_spike.prompts import alt_text, contrast

logger = logging.getLogger(__name__)

# Map axe-core rule IDs to the prompt module that handles them.
# Add new rules here as the spike grows.
SUPPORTED_RULES: Final[set[str]] = {"image-alt", "color-contrast"}

DEFAULT_MODEL = "claude-sonnet-4-6"
DEFAULT_MAX_TOKENS = 1024


class Remediator:
    """Wraps the Anthropic client with the project-specific patching logic.

    The class is instantiated once per request so we can override the model
    or max tokens cheaply during tests without monkeypatching.
    """

    def __init__(
        self,
        *,
        api_key: str | None = None,
        model: str | None = None,
        max_tokens: int = DEFAULT_MAX_TOKENS,
    ) -> None:
        api_key = api_key or os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            raise RuntimeError(
                "ANTHROPIC_API_KEY is not set. Configure it in .env or the environment."
            )
        self._client = Anthropic(api_key=api_key)
        self._model = model or os.environ.get("CLAUDE_MODEL", DEFAULT_MODEL)
        self._max_tokens = max_tokens

    def remediate(self, violation: Violation) -> Patch | None:
        """Generate a patch for one violation, or None if the rule is unsupported."""
        if violation.rule_id not in SUPPORTED_RULES:
            logger.debug("Skipping unsupported rule", extra={"rule_id": violation.rule_id})
            return None

        if not violation.nodes:
            logger.warning("Violation has no nodes, cannot remediate", extra={
                "rule_id": violation.rule_id,
            })
            return None

        if violation.rule_id == "image-alt":
            return self._remediate_alt_text(violation)
        if violation.rule_id == "color-contrast":
            return self._remediate_contrast(violation)

        return None  # Defensive — should be unreachable due to SUPPORTED_RULES check.

    # ------------------------------------------------------------------
    # Per-rule remediation strategies
    # ------------------------------------------------------------------

    def _remediate_alt_text(self, violation: Violation) -> Patch:
        primary_node = violation.nodes[0]
        user_message = alt_text.build_prompt(violation)
        patched_html = self._invoke(
            system=alt_text.SYSTEM_PROMPT,
            user_message=user_message,
        ).strip()

        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=primary_node.target[0] if primary_node.target else "unknown",
            original_html=primary_node.html,
            patched_html=patched_html,
            explanation=(
                "Added a meaningful alt attribute generated by Claude from the page "
                "context. Review for accuracy before merging."
            ),
            confidence="medium",
        )

    def _remediate_contrast(self, violation: Violation) -> Patch:
        primary_node = violation.nodes[0]
        user_message = contrast.build_prompt(violation)
        raw_response = self._invoke(
            system=contrast.SYSTEM_PROMPT,
            user_message=user_message,
        )

        try:
            payload = json.loads(raw_response)
            patched_color = payload["patched_color"]
            explanation = payload["explanation"]
        except (json.JSONDecodeError, KeyError) as exc:
            logger.warning(
                "Claude returned malformed contrast response, falling back",
                extra={"error": str(exc), "response": raw_response[:200]},
            )
            patched_color = "#000000"
            explanation = "Claude response could not be parsed; defaulted to black."

        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=primary_node.target[0] if primary_node.target else "unknown",
            original_html=primary_node.html,
            patched_html=self._inject_color(primary_node.html, patched_color),
            explanation=explanation,
            confidence="medium",
        )

    # ------------------------------------------------------------------
    # Low-level Anthropic call
    # ------------------------------------------------------------------

    def _invoke(self, *, system: str, user_message: str) -> str:
        """Call Claude and return the first text block."""
        messages: list[MessageParam] = [{"role": "user", "content": user_message}]
        response = self._client.messages.create(
            model=self._model,
            max_tokens=self._max_tokens,
            system=system,
            messages=messages,
        )
        for block in response.content:
            if block.type == "text":
                return block.text
        raise RuntimeError("Claude returned no text content.")

    @staticmethod
    def _inject_color(html: str, color: str) -> str:
        """Naive helper: append an inline style to override the foreground color.

        Production will rewrite the actual CSS rule that owns the color, but
        for the spike an inline style is enough to demonstrate the patch shape.
        """
        if 'style="' in html:
            return html.replace('style="', f'style="color: {color}; ', 1)
        return html.replace("<", f'<span style="color: {color}">', 1) + "</span>"
