"""Generate code patches using a pluggable LLMProvider.

The remediator does not know which model is behind the provider. It only
calls `provider.complete(system, user_message)` and parses the response.
Swapping Claude for AWS Bedrock or OpenAI requires zero changes here.
"""

from __future__ import annotations

import json
import logging
from typing import Final

from faro_spike.llm.provider import LLMCompletionError, LLMProvider
from faro_spike.models import Patch, Violation
from faro_spike.prompts import alt_text, contrast

logger = logging.getLogger(__name__)

# Map axe-core rule IDs to the prompt module that handles them.
SUPPORTED_RULES: Final[set[str]] = {"image-alt", "color-contrast"}

DEFAULT_MAX_TOKENS = 1024


class Remediator:
    """Wraps an LLMProvider with the project-specific patching strategies.

    Construct with a concrete provider (typically built via
    `faro_spike.llm.build_provider()`) so the rest of the worker stays
    vendor-agnostic.
    """

    def __init__(
        self,
        *,
        provider: LLMProvider,
        max_tokens: int = DEFAULT_MAX_TOKENS,
    ) -> None:
        self._provider = provider
        self._max_tokens = max_tokens

    def remediate(self, violation: Violation) -> Patch | None:
        """Generate a patch for one violation, or None if the rule is unsupported."""
        if violation.rule_id not in SUPPORTED_RULES:
            logger.debug("Skipping unsupported rule", extra={"rule_id": violation.rule_id})
            return None

        if not violation.nodes:
            logger.warning(
                "Violation has no nodes, cannot remediate",
                extra={"rule_id": violation.rule_id},
            )
            return None

        if violation.rule_id == "image-alt":
            return self._remediate_alt_text(violation)
        if violation.rule_id == "color-contrast":
            return self._remediate_contrast(violation)

        return None  # Defensive — unreachable given SUPPORTED_RULES.

    # ------------------------------------------------------------------
    # Per-rule remediation strategies
    # ------------------------------------------------------------------

    def _remediate_alt_text(self, violation: Violation) -> Patch:
        primary_node = violation.nodes[0]
        user_message = alt_text.build_prompt(violation)
        patched_html = self._invoke(
            system=alt_text.SYSTEM_PROMPT,
            user_message=user_message,
        ).strip()

        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=primary_node.target[0] if primary_node.target else "unknown",
            original_html=primary_node.html,
            patched_html=patched_html,
            explanation=(
                f"Added a meaningful alt attribute generated by {self._provider.name} "
                "from the page context. Review for accuracy before merging."
            ),
            confidence="medium",
        )

    def _remediate_contrast(self, violation: Violation) -> Patch:
        primary_node = violation.nodes[0]
        user_message = contrast.build_prompt(violation)
        raw_response = self._invoke(
            system=contrast.SYSTEM_PROMPT,
            user_message=user_message,
        )

        try:
            payload = json.loads(raw_response)
            patched_color = payload["patched_color"]
            explanation = payload["explanation"]
        except (json.JSONDecodeError, KeyError) as exc:
            logger.warning(
                "Provider returned malformed contrast response, falling back",
                extra={
                    "provider": self._provider.name,
                    "error": str(exc),
                    "response": raw_response[:200],
                },
            )
            patched_color = "#000000"
            explanation = (
                f"{self._provider.name} response could not be parsed; "
                "defaulted to black. Manual review required."
            )

        return Patch(
            violation_rule_id=violation.rule_id,
            target_selector=primary_node.target[0] if primary_node.target else "unknown",
            original_html=primary_node.html,
            patched_html=self._inject_color(primary_node.html, patched_color),
            explanation=explanation,
            confidence="medium",
        )

    # ------------------------------------------------------------------
    # Provider call wrapper
    # ------------------------------------------------------------------

    def _invoke(self, *, system: str, user_message: str) -> str:
        """Delegate to the configured LLMProvider with consistent error context."""
        try:
            return self._provider.complete(
                system=system,
                user_message=user_message,
                max_tokens=self._max_tokens,
            )
        except LLMCompletionError:
            raise
        except Exception as exc:  # noqa: BLE001
            raise LLMCompletionError(
                f"Provider {self._provider.name} raised unexpected error: {exc}"
            ) from exc

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _inject_color(html: str, color: str) -> str:
        """Naive helper: append an inline style to override the foreground color.

        Production will rewrite the actual CSS rule that owns the color, but
        for the spike an inline style is enough to demonstrate the patch shape.
        """
        if 'style="' in html:
            return html.replace('style="', f'style="color: {color}; ', 1)
        return html.replace("<", f'<span style="color: {color}">', 1) + "</span>"
